CI - Test that quickstart-chat builds (#197)
* Test quickstart-chat in CI

* fix?

* ignore diffs containing SpacetimeDB commit

* prettier config

* fix?

* [REVERT THIS TEST COMMIT] add diff to module bindings

* revert previous test commit

* [REVERT THIS TEST COMMIT] introduce a typechecking error

* revert previous test commit

* tiny review

---------

Co-authored-by: Zeke Foppa <bfops@users.noreply.github.com>

diff --git a/sdks/typescript/.github/workflows/test.yml b/sdks/typescript/.github/workflows/test.yml
--- a/sdks/typescript/.github/workflows/test.yml
+++ b/sdks/typescript/.github/workflows/test.yml
@@ -70,71 +70,77 @@ jobs:
       #     echo "branch=$branch" >> $GITHUB_OUTPUT
       #     echo "Using SpacetimeDB branch from file: $branch"
 
-      # - name: Checkout SpacetimeDB
-      #   uses: actions/checkout@v4
-      #   with:
-      #     repository: clockworklabs/SpacetimeDB
-      #     ref: ${{ steps.extract-branch.outputs.branch }}
-      #     path: SpacetimeDB
+      - name: Checkout SpacetimeDB
+        uses: actions/checkout@v4
+        with:
+          repository: clockworklabs/SpacetimeDB
+      #    ref: ${{ steps.extract-branch.outputs.branch }}
+          path: SpacetimeDB
 
-      # - name: Install Rust toolchain
-      #   uses: dtolnay/rust-toolchain@stable
+      - name: Install Rust toolchain
+        uses: dtolnay/rust-toolchain@stable
 
-      # - name: Cache Rust dependencies
-      #   uses: Swatinem/rust-cache@v2
-      #   with:
-      #     workspaces: SpacetimeDB/modules/quickstart-chat
-      #     shared-key: quickstart-chat-test
+      - name: Cache Rust dependencies
+        uses: Swatinem/rust-cache@v2
+        with:
+          workspaces: SpacetimeDB/modules/quickstart-chat
+          shared-key: quickstart-chat-test
 
-      # - name: Install SpacetimeDB CLI from the local checkout
+      - name: Install SpacetimeDB CLI from the local checkout
+        run: |
+          cargo install --force --path SpacetimeDB/crates/cli --locked --message-format=short
+          cargo install --force --path SpacetimeDB/crates/standalone --locked --message-format=short
+          # Add a handy alias using the old binary name, so that we don't have to rewrite all scripts (incl. in submodules).
+          rm -f $HOME/.cargo/bin/spacetime
+          ln -s $HOME/.cargo/bin/spacetimedb-cli $HOME/.cargo/bin/spacetime
+          # Clear any existing information
+          spacetime server clear -y
+        env:
+          # Share the target directory with our local project to avoid rebuilding same SpacetimeDB crates twice.
+          CARGO_TARGET_DIR: SpacetimeDB/modules/quickstart-chat/target
+
+      - name: Generate client bindings
+        working-directory: SpacetimeDB/modules/quickstart-chat
+        run: |
+          spacetime generate --lang typescript --out-dir ../../../examples/quickstart-chat/src/module_bindings
+          pnpm lint --write
+
+      - name: Check for changes
+        run: |
+          # This was copied from SpacetimeDB/tools/check-diff.sh.
+          # It's required because `spacetime generate` creates lines with the SpacetimeDB commit
+          # version, which would make this `git diff` check very brittle if included.
+          PATTERN='^// This was generated using spacetimedb cli version.*'
+          if ! git diff --exit-code --ignore-matching-lines="$PATTERN" -- examples/quickstart-chat/src/module_bindings; then
+            echo "Error: Bindings are dirty. Please generate bindings again and commit them to this branch."
+            exit 1
+          fi
+
+      # - name: Start SpacetimeDB
       #   run: |
-      #     cargo install --force --path SpacetimeDB/crates/cli --locked --message-format=short
-      #     cargo install --force --path SpacetimeDB/crates/standalone --locked --message-format=short
-      #     # Add a handy alias using the old binary name, so that we don't have to rewrite all scripts (incl. in submodules).
-      #     rm $HOME/.cargo/bin/spacetime || echo "haven't run on this host before"
-      #     ln -s $HOME/.cargo/bin/spacetimedb-cli $HOME/.cargo/bin/spacetime
-      #     # Clear any existing information
-      #     spacetime server clear -y
-      #   env:
-      #     # Share the target directory with our local project to avoid rebuilding same SpacetimeDB crates twice.
-      #     CARGO_TARGET_DIR: SpacetimeDB/modules/quickstart-chat/target
+      #     spacetime start &
+      #     disown
 
-      # - name: Generate client bindings
+      # - name: Publish module to SpacetimeDB
       #   working-directory: SpacetimeDB/modules/quickstart-chat
       #   run: |
-      #     spacetime generate --lang typescript --out-dir ../../../examples/quickstart-chat/src/module_bindings
-      #     pnpm lint --write
+      #     spacetime logout && spacetime login --server-issued-login local
+      #     spacetime publish -s local quickstart-chat -c -y
 
-      # - name: Check for changes
+      # - name: Publish module to SpacetimeDB
+      #   working-directory: SpacetimeDB/modules/quickstart-chat
       #   run: |
-      #     git diff --exit-code examples/quickstart-chat/src/module_bindings || {
-      #         echo "Error: Bindings are dirty. Please generate bindings again and commit them to this branch."
-      #         exit 1
-#      - name: Start SpacetimeDB
-#        run: |
-#          spacetime start &
-#          disown
-#
-#      - name: Publish module to SpacetimeDB
-#        working-directory: SpacetimeDB/modules/quickstart-chat
-#        run: |
-#          spacetime logout && spacetime login --server-issued-login local
-#          spacetime publish -s local quickstart-chat -c -y
-#
-#      - name: Check if SpacetimeDB process is running
-#        run: |
-#          echo "Currently running spacetime processes:"
-#          pgrep -laf spacetime || echo "No spacetime process found."
-#
-#      - name: Publish module to SpacetimeDB
-#        working-directory: SpacetimeDB/modules/quickstart-chat
-#        run: |
-#          spacetime logs quickstart-chat
-#
-#      - name: Run all tests recursively
-#        run: pnpm test
-#
-#      # Run this step always, even if the previous steps fail
-#      - name: Print rows in the user table
-#        if: always()
-#        run: spacetime sql quickstart-chat "SELECT * FROM user"
+      #     spacetime logs quickstart-chat
+
+      - name: Check that quickstart-chat builds
+        working-directory: examples/quickstart-chat
+        run: pnpm build
+
+      # - name: Run quickstart-chat tests
+      #   working-directory: examples/quickstart-chat
+      #   run: pnpm test
+      #
+      # # Run this step always, even if the previous steps fail
+      # - name: Print rows in the user table
+      #   if: always()
+      #   run: spacetime sql quickstart-chat "SELECT * FROM user"
