Updated pre-commit hook to do the formatting and then add to git

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -49,4 +49,26 @@
 # exec git diff-index --check --cached $against --
 
 # Run the rust formatter
-cargo +nightly fmt
+#!/bin/bash -e
+declare -a rust_files=()
+files=$(git diff-index --name-only HEAD)
+echo 'Formatting source files'
+for file in $files; do
+    if [ ! -f "${file}" ]; then
+        continue
+    fi
+    if [[ "${file}" == *.rs ]]; then
+        rust_files+=("${file}")
+    fi
+done
+if [ ${#rust_files[@]} -ne 0 ]; then
+    command -v cargo +nightly fmt >/dev/null 2>&1 || { echo >&2 "Rustfmt is required but it's not installed. Aborting."; exit 1; }
+    $(command -v cargo +nightly fmt) ${rust_files[@]} &
+fi
+wait
+if [ ${#rust_files[@]} -ne 0 ]; then
+    git add ${rust_files[@]}
+    echo "Formatting done, changed files: ${rust_files[@]}"
+else
+    echo "No changes, formatting skipped"
+fi
