[bfops/deny-merge-labels]: fix?

diff --git a/.github/workflows/check-merge-labels.yml b/.github/workflows/check-merge-labels.yml
--- a/.github/workflows/check-merge-labels.yml
+++ b/.github/workflows/check-merge-labels.yml
@@ -22,4 +22,6 @@ jobs:
         if: |
           contains(github.event.pull_request.labels.*.name, 'abi-break') ||
           contains(github.event.pull_request.labels.*.name, 'breaking change')
-        run: echo "::error::This is a breaking change." && exit 1
+        run: |
+          echo "::error ::This is a breaking change." >/dev/stderr
+          exit 1
