[bfops/check-smoketests]: check for changes

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -163,6 +163,13 @@ jobs:
           }
           cargo ci smoketests -- --test-threads=1          
 
+      - name: Check for changes
+        run: |
+          tools/check-diff.sh crates/smoketests || {
+              echo 'Error: There is a diff in the smoketests directory.'
+              exit 1
+          }
+
   smoketests-python:
     needs: [lints]
     name: Smoketests (Python Legacy) (${{matrix.name}})
