[lisandro/godot-blackholio]: godot CI WIP

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1232,6 +1232,29 @@ jobs:
       #   if: always()
       #   run: spacetime sql quickstart-chat "SELECT * FROM user"
 
+  godot_tests:
+    runs-on: spacetimedb-new-runner-2
+    steps:
+      - name: Install Godot
+        shell: bash
+        run: |
+          GODOT_VERSION=4.6.2
+          GODOT_STATUS=stable
+          GODOT_BIN=Godot_v${GODOT_VERSION}-${GODOT_STATUS}_linux.x86_64
+
+          curl -L -o godot.zip \
+            "https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}-${GODOT_STATUS}/${GODOT_BIN}.zip"
+
+          unzip godot.zip
+          chmod +x "${GODOT_BIN}"
+          sudo mv "${GODOT_BIN}" /usr/local/bin/godot
+
+          godot --version
+
+      - name: Replace this step
+        # Fail until we've integrated Godot SDK
+        run: exit 1
+
   version_upgrade_check:
     runs-on: spacetimedb-new-runner-2
     steps:
