[bfops/ci-csharp-check]: CI - Check C# generated files

diff --git a/.github/workflows/csharp-test.yml b/.github/workflows/csharp-test.yml
--- a/.github/workflows/csharp-test.yml
+++ b/.github/workflows/csharp-test.yml
@@ -83,15 +83,18 @@ jobs:
           CARGO_TARGET_DIR: demo/Blackholio/server-rust/target
 
       - name: Check quickstart-chat bindings are up to date
-        working-directory: sdks/csharp/examples~/quickstart-chat
         run: |
-          bash ../../tools~/gen-quickstart.sh "${GITHUB_WORKSPACE}"
-          # This was copied from tools/check-diff.sh.
-          # It's required because `spacetime generate` creates lines with the SpacetimeDB commit
-          # version, which would make this `git diff` check very brittle if included.
-          PATTERN='^// This was generated using spacetimedb cli version.*'
-          git diff --exit-code --ignore-matching-lines="$PATTERN" -- . || {
+          bash sdks/csharp/tools~/gen-quickstart.sh "${GITHUB_WORKSPACE}"
+          tools/check-diff.sh sdks/csharp/examples~/quickstart-chat || {
               echo "Error: quickstart-chat bindings have changed. Please regenerate the bindings and commit them to this branch."
+              exit 1
+          }
+
+      - name: Check client-api bindings are up to date
+        run: |
+          bash sdks/csharp/tools~/gen-client-api.sh "${GITHUB_WORKSPACE}"
+          tools/check-diff.sh sdks/csharp/src/SpacetimeDB/ClientApi || {
+              echo "Error: Client API are dirty. Please generate bindings again and commit them to this branch."
               exit 1
           }
 
@@ -101,11 +104,7 @@ jobs:
 
       - name: Check for changes
         run: |
-          # This was copied from tools/check-diff.sh.
-          # It's required because `spacetime generate` creates lines with the SpacetimeDB commit
-          # version, which would make this `git diff` check very brittle if included.
-          PATTERN='^// This was generated using spacetimedb cli version.*'
-          git diff --exit-code --ignore-matching-lines="$PATTERN" -- demo/Blackholio/client-unity/Assets/Scripts/autogen || {
+          tools/check-diff.sh demo/Blackholio/client-unity/Assets/Scripts/autogen || {
               echo "Error: Bindings are dirty. Please generate bindings again and commit them to this branch."
               exit 1
           }
@@ -124,7 +123,12 @@ jobs:
           disown
 
       - name: Run regression tests
-        run: bash sdks/csharp/tools~/run-regression-tests.sh .
+        run: |
+          bash sdks/csharp/tools~/run-regression-tests.sh "${GITHUB_WORKSPACE}"
+          tools/check-diff.sh sdks/csharp/examples~/regression-tests || {
+              echo "Error: Bindings are dirty. Please generate bindings again and commit them to this branch."
+              exit 1
+          }
 
       - name: Publish unity-tests module to SpacetimeDB
         working-directory: demo/Blackholio/server-rust
