CI - Check C# quickstart-chat bindings are up to date (#2979)
Co-authored-by: Zeke Foppa <bfops@users.noreply.github.com>

diff --git a/.github/workflows/csharp-test.yml b/.github/workflows/csharp-test.yml
--- a/.github/workflows/csharp-test.yml
+++ b/.github/workflows/csharp-test.yml
@@ -76,6 +76,19 @@ jobs:
           # Share the target directory with our local project to avoid rebuilding same SpacetimeDB crates twice.
           CARGO_TARGET_DIR: demo/Blackholio/server-rust/target
 
+      - name: Check quickstart-chat bindings are up to date
+        working-directory: sdks/csharp/examples~/quickstart-chat
+        run: |
+          spacetime generate --lang csharp --out-dir client/module_bindings --project-path server
+          # This was copied from tools/check-diff.sh.
+          # It's required because `spacetime generate` creates lines with the SpacetimeDB commit
+          # version, which would make this `git diff` check very brittle if included.
+          PATTERN='^// This was generated using spacetimedb cli version.*'
+          git diff --exit-code --ignore-matching-lines="$PATTERN" -- . || {
+              echo "Error: quickstart-chat bindings have changed. Please regenerate the bindings and commit them to this branch."
+              exit 1
+          }
+
       - name: Generate client bindings
         working-directory: demo/Blackholio/server-rust
         run: bash ./generate.sh -y
