[bfops/fix-ci]: fix and cleanups

diff --git a/.github/workflows/typescript-test.yml b/.github/workflows/typescript-test.yml
--- a/.github/workflows/typescript-test.yml
+++ b/.github/workflows/typescript-test.yml
@@ -101,10 +101,15 @@ jobs:
             cargo clean -p v8 || true
             cargo build -p v8
           fi
+          if ! [ -f "${CARGO_TARGET_DIR}"/release/gn_out/obj/librusty_v8.a ]; then
+            echo "Could not find v8 output file librusty_v8.a; rebuilding manually."
+            cargo clean --release -p v8 || true
+            cargo build --release -p v8
+          fi
 
       - name: Install SpacetimeDB CLI from the local checkout
         run: |
-          BIN="${GITHUB_WORKSPACE}/.cargo/bin"
+          BIN="$HOME/.cargo/bin"
           echo "$BIN" >> "$GITHUB_PATH"
           cargo install --force --path crates/cli --locked --message-format=short
           cargo install --force --path crates/standalone --locked --message-format=short
@@ -112,18 +117,6 @@ jobs:
           ln -sf "$BIN/spacetimedb-cli" "$BIN/spacetime"
           # Clear any existing information
           spacetime server clear -y
-
-      # This step shouldn't be needed, but somehow we end up with caches that are missing librusty_v8.a.
-      # This may be due to reusing CARGO_TARGET_DIR while mixing different build strategies (`cargo install` and `cargo build -p`).
-      # However, this fix seems to work.
-      - name: Check v8 outputs
-        run: |
-          find "${CARGO_TARGET_DIR}"/ -type f | grep '[/_]v8' || true
-          if ! [ -f "${CARGO_TARGET_DIR}"/debug/gn_out/obj/librusty_v8.a ]; then
-            echo "Could not find v8 output file librusty_v8.a; rebuilding manually."
-            cargo clean -p v8 || true
-            cargo build -p v8
-          fi
 
       - name: Generate client bindings
         working-directory: templates/chat-react-ts
